"""Agregar Plantillas

Revision ID: 1fcd24c91f2b
Revises: 66ae4875741c
Create Date: 2024-11-22 16:24:40.128802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcd24c91f2b'
down_revision = '66ae4875741c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Plantillas', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('RecursosPlantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preparacion', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bbp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('r_dev', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('r_pya', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pi_pya', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pi_deply', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('acompanamiento', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_dias', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_venta', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('costo_venta', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('margen_venta', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('porcentaje_margen', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.alter_column('tarifa_lista',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('tarifa_venta',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RecursosPlantilla', schema=None) as batch_op:
        batch_op.alter_column('tarifa_venta',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('tarifa_lista',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('porcentaje_margen')
        batch_op.drop_column('margen_venta')
        batch_op.drop_column('costo_venta')
        batch_op.drop_column('total_venta')
        batch_op.drop_column('total_dias')
        batch_op.drop_column('acompanamiento')
        batch_op.drop_column('pi_deply')
        batch_op.drop_column('pi_pya')
        batch_op.drop_column('r_pya')
        batch_op.drop_column('r_dev')
        batch_op.drop_column('bbp')
        batch_op.drop_column('preparacion')

    with op.batch_alter_table('Plantillas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
