"""Agregar campo solution a Conceptos

Revision ID: 428aca298c28
Revises: 731b3ef15161
Create Date: 2024-10-18 12:39:12.330703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428aca298c28'
down_revision = '731b3ef15161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ConceptosServicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gerente_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'Users', ['gerente_id'], ['id'])

    with op.batch_alter_table('CotizacionesSolicitadas', schema=None) as batch_op:
        batch_op.drop_constraint('FK__Cotizacio__geren__39237A9A', type_='foreignkey')
        batch_op.drop_column('gerente_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CotizacionesSolicitadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gerente_id', sa.VARCHAR(length=36, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('FK__Cotizacio__geren__39237A9A', 'Users', ['gerente_id'], ['id'])

    with op.batch_alter_table('ConceptosServicio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gerente_id')

    # ### end Alembic commands ###
