"""Permitir nombre null clientes

Revision ID: 568f5700ebbc
Revises: c4b091ecacd7
Create Date: 2024-11-22 12:41:39.736233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568f5700ebbc'
down_revision = 'c4b091ecacd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'),
               nullable=False)

    # ### end Alembic commands ###
