"""Agregar campo solution a Conceptos

Revision ID: 83f1b4e9560c
Revises: 428aca298c28
Create Date: 2024-10-23 12:12:15.124066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f1b4e9560c'
down_revision = '428aca298c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RecursosCotizacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_dias', sa.Integer(), nullable=False))
        batch_op.drop_column('total_horas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RecursosCotizacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_horas', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('total_dias')

    # ### end Alembic commands ###
